server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.139.129:3306/db_study?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: YuI,0601
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 20
      minimum-idle: 5
      login-timeout: 1000
      idle-timeout: 1000
      connection-timeout: 1000


